modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="exnihiloreborn"
version="${mod_version}"
displayName="Ex Nihilo Reborn"
credits="Herobrine knows all. Thanks to Erasmus_Crowley for the original 1.7 mod"
authors="TheDarkColour"
description='''
Bringing back the original Ex Nihilo.
'''
[[dependencies.exnihiloreborn]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.exnihiloreborn]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"
